name: CI/CD SMA Backend

on:
  push:
    branches:
      - main
    paths:
      - 'sma-core-service/**'
      - '.github/workflows/deploy-prod.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B clean package -DskipTests
        working-directory: sma-core-service

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ vars.DOCKER_USERNAME }}/sma-core-service:latest ./sma-core-service

      - name: Push Docker image
        run: docker push ${{ vars.DOCKER_USERNAME }}/sma-core-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: PROD
    steps:
      - name: SSH to server and deploy Java service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST_IP }}
          username: root
          key: ${{ secrets.SECRET_KEY }}
          script: |
            cd /var/docker/sma
            echo "Deploying Java Core Service..."
            docker compose pull sma-core-service
            docker compose up -d sma-core-service
            docker image prune -f
            echo "Deployment completed!"
            docker ps | grep sma-core-service
